env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:node/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  max-len:
    - error
    - code: 120
      tabWidth: 2
      ignoreUrls: true
      ignoreComments: false
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
