env:
  browser: false
  commonjs: true
  es2021: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
rules:
  prettier/prettier:
    - error
  eqeqeq:
    - warn
  max-len:
    - error
    - code: 120
      tabWidth: 2
      ignoreUrls: true
      ignoreComments: false
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
