name: Build
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: stucode
          POSTGRES_USER: stucode
          POSTGRES_PASSWORD: stucode
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust the Node.js version as needed
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        id: sonar
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Notify Slack
        if: ${{ always() }} # Se ejecutará siempre, independientemente del resultado del paso anterior
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ ${{ steps.sonar.outcome }} == 'failure' ]; then
            curl -X POST -H 'Content-type: application/json' --data '{"text":"❌ El escaneo de SonarCloud ha fallado."}' $SLACK_WEBHOOK_URL
          else
            curl -X POST -H 'Content-type: application/json' --data '{"text":"✅ El escaneo de SonarCloud ha finalizado con éxito."}' $SLACK_WEBHOOK_URL
          fi
